# Generated by Django 5.0.7 on 2024-08-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diabetesassessment",
            name="Gender",
            field=models.IntegerField(),
        ),
    ]
